server {
  listen 8080;
  server_name _;
  server_tokens off;

  root /usr/share/nginx/html;
  index index.html;
  charset utf-8;

  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/css application/javascript application/json image/svg+xml;

  error_page 404 /404.html;

  location / {
    try_files $uri.html $uri/index.html $uri =404;
  }

  location = /404.html {
    internal;
  }
}
